--[[
THIS IS MY SCRIPT FILE
]]--

PROGRAM_NAME = "C++ Lua Script Testing"
PROGRAM_VERSION = "0.1A"
SCREENWIDTH = 1920	
SCREENHEIGHT = 1200
COLORDEPTH = 32
FULLSCREEN = false
MUSIC_VOLUME = 5
SOUND_VOLUME = 5
GRAVITY = 9
FRICTION = 1
MAX_VELOCITY = 1
MAX_ACCELERATION = 1
